### ISSUE TITLE
Information for contributors

### ISSUE THREAD

**Issue by gabrielpoca** [subvisual/alchemyconf.com#6]
There are open issues for the missing components. Before you start working on something, go there and say what you're going to do. Each issue corresponds to a page. If something's missing, add it to a task list on the issue's description. If what you need to change doesn't belong to a page, create an issue.

Assign yourself to the issues you're working on so we can stay in sync.

Relevant link:

* [Figma](https://www.figma.com/file/3kyRx3ObWpUERLsiJ9f6xl/Alchemy-Conf?node-id=571%3A301)

**Comment by frm** [comment]
Can we move this to a contributing.md?

**Comment by gabrielpoca** [comment]
Sure, although I would just close it. It's a website for a single edition of the conference. I'm not sure that's worth the effort to make this contributor friendly.
